services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8888:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
